### ISSUE TITLE
Headphone Jack fails without Power Adapter - Loud Noise

### ISSUE THREAD

**Issue by mceykes** [LuletterSoul/Dell-XPS-15-9570-macOS-Mojave#73]
Has anyone else this issue? When I unplug the power adapter, the headphone jack continues to work for a while, then after a random amount of time, (usually a few seconds but also goes up to 10-20 minutes) it produces loud, pink noise that does not stop when I pause the current audio / music. 

I have the 1080p model, and installed the latest EFI, with BIOS at Version 1.13.0. I currently have the layout-id set to 30, I also tried 72 but then there was no sound at all.

I've been trying and one time, when restarting the system, this debug message appeared:

![Headphone Jack Debug?](https://user-images.githubusercontent.com/55514163/67642983-db44f300-f911-11e9-93ef-7fae2f71356b.JPG)

Afterwards it was okay and Audio seemed to worked fine. After restarting the system again, it was back to normal and failed immediately.

Any Ideas? Thanks!

**Comment by artan13** [comment]
Hi first of all I just want to say thanks for your great work! I am also having the same issue with getting a loud buzzing noise coming from my headphone jack. I am having this issue while running on battery. Tried changing layout id to 72. That made the sound worse. Any ideas, on how to resolve this issue.

**Comment by mceykes** [comment]
Does anyone know what range of layout ids are available or make sense to try out? (like 1-100?) I'd be happy to try all of them if there is a list.

**Comment by artan13** [comment]
I read that it's between 1-188. Just testing now.

**Comment by mceykes** [comment]
https://github.com/acidanthera/AppleALC/wiki/Supported-codecs
here it says layout 3, 11, 13, 21, 22, 28, 29, 30, 32, 47, 66, 72, 99 are supported for ALC 298. also just testing..

**Comment by artan13** [comment]
Only ones working for me were 21,22,29,30. However my issue of the buzzing
noise still occurs whenever laptop wakes from sleep. So I guess I'll just
have to stop laptop from falling a sleep.

**Comment by mceykes** [comment]
I also tried them all and the same ones work at first: 21,22,29,30 - however, the only one that works for more than a few seconds has been 21. I will try this one tomorrow for a longer period of time and report how it works. 
I also have the issue with sleep that you describe. Only noticed it now when testing it.. haha. Yeah better keep the laptop awake for now.

**Comment by mceykes** [comment]
This morning layout id 21 also failed a few seconds after I started playing some audio. @artan13 but you also have the same issue that it makes loud noise when you play audio, regardless of the sleep issue?

**Comment by artan13** [comment]
Hi. I've gone ahead and used bravariancake's guide for the 9570. It has
fixed the main audio issues. But my audio still has buzzing noise issue if
I put it to sleep so I'm using amphetamine app to keep it awake. I've
linked the guide below.

https://github.com/bavariancake/XPS9570-macOS

**Comment by mceykes** [comment]
I just tried this one but the audio issue remains. Did you do any tweaks to his EFI? I noticed that the trackpad was not lagging as much as the current EFI LuLetterSoul provided. How is it with you?

**Comment by artan13** [comment]
I didn't need to do any tweaks. Followed the guide to the letter and
everything just works.

**Comment by OldDream** [comment]
guys， just use  this https://github.com/jardenliu/ALC298PlugFix,with layoutId 30,everything works fine

**Comment by yongjiajun** [comment]
> guys， just use this https://github.com/jardenliu/ALC298PlugFix,with layoutId 30,everything works fine

The ALC298PlugFix by @jardenliu is no longer being maintained, however please use ALCPlugFix by Sniki which includes the wake from sleep audio buzzing bug:
https://github.com/Sniki/ALCPlugFix

For me, even after applying the fix, buzzing now only occurs seconds later after unplugging my laptop from the charger when I have my earphones plugged in. FYI I'm using layout-id 30.

**Comment by yongjiajun** [comment]
I fixed the issue by removing ALC298PlugFix (launch daemons, binaries and stuff) and installing [ComboJack](https://github.com/hackintosh-stuff/ComboJack) by @hackintosh-stuff. 

Everything works fine even after sleep and buzzing no longer occurs. WIth ComboJack, I also get to use the in-line microphone with the _line-in_ option when selecting _headset_ in the ComboJack pop-up. FYI I'm using layout-id 30.

**Comment by artan13** [comment]
Hi

Thanks for your advice. Do you know how to remove launch demons and
binaries without having to reinstall the whole OS.

Thanks.

**Comment by yongjiajun** [comment]
> Hi Thanks for your advice. Do you know how to remove launch demons and binaries without having to reinstall the whole OS. Thanks.

Simply run these commands in your terminal:
```bash
sudo launchctl unload -w /Library/LaunchAgents/good.win.ALCPlugFix.plist
sudo rm -rf /usr/bin/ALCPlugFix
sudo rm -rf /usr/bin/hda-verb
sudo rm -rf /Library/LaunchAgents/good.win.ALCPlugFix.plist
```
then install [ComboJack](https://github.com/hackintosh-stuff/ComboJack) (remember to remove CodecCommander kext and add VerbStub kext).

**Comment by artan13** [comment]
> > Hi Thanks for your advice. Do you know how to remove launch demons and binaries without having to reinstall the whole OS. Thanks.
> 
> Simply run these commands in your terminal:
> 
> ```shell
> sudo launchctl unload -w /Library/LaunchAgents/good.win.ALCPlugFix.plist
> sudo rm -rf /usr/bin/ALCPlugFix
> sudo rm -rf /usr/bin/hda-verb
> sudo rm -rf /Library/LaunchAgents/good.win.ALCPlugFix.plist
> ```
> 
> then install [ComboJack](https://github.com/hackintosh-stuff/ComboJack) (remember to remove CodecCommander kext and add VerbStub kext).

Hi. Audio works perfectly now. Thanks

**Comment by mceykes** [comment]
thanks that works perfectly.

**Comment by mceykes** [comment]
hey guys can you help me out again? 
I just noticed, that the ComboJack install was not successful - what made it work was the EFI I used by Bavarian Cake (I installed it at the same time - seemed to work so I did not worry about it). However, I had some other issues with BavarianCakes EFI so I switched to Luletters' and have now trouble installing ComboJack als @yongjiajun describes.

I did not have ALCPlugFix installed so I jumped right to the ComboJack installation yesterday. I followed the steps that are outlined in the readme (delete CodecCommander and add VerbStub) and when I paste the install.sh in the Terminal it keeps hanging at "Init.codec." for ever. Any Ideas what I might be missing? 
![Screenshot 2019-11-15 at 12 30 54](https://user-images.githubusercontent.com/55514163/68940568-cdadbb00-07a3-11ea-8cc0-38704c7c38fc.png)

After a while it says "Jack not ready. Checking again in 1 second..." and this line repeats endlessly

**Comment by mceykes** [comment]
Nevermind - I got it working. Thanks.

**Comment by erenatas** [comment]
@mceykes Can you please tell how did you make it step by step so that we can do it?

**Comment by mceykes** [comment]
So I did not have ALCPlugFix installed before. And I just did this:
Download ComboJack and place it on your System drive somewhere.
Delete CodecComander kext in your EFI and place the Verbstub.kext there.
Open the Install.sh txt document
Open Terminal

run these commands:
cd dirname (insert your directory example: /Users/YOURNAME/ComboJack)

Then skip the legacy part in the Install.sh and just run this. Again insert the directoryname for "dirname":

cd "$( dirname "${BASH_SOURCE[0]}" )"
mkdir -p /usr/local/sbin
sudo cp ComboJack /usr/local/sbin
sudo chmod 755 /usr/local/sbin/ComboJack
sudo chown root:wheel /usr/local/sbin/ComboJack
sudo spctl --add /usr/local/sbin/ComboJack
sudo cp hda-verb /usr/local/sbin
#sudo chmod 755 /usr/local/sbin/hda-verb
#sudo chown root:wheel /usr/local/sbin/hda-verb
sudo mkdir -p /usr/local/share/ComboJack/
sudo cp Headphone.icns /usr/local/share/ComboJack/
sudo chmod 644 /usr/local/share/ComboJack/Headphone.icns
sudo cp l10n.json /usr/local/share/ComboJack/
sudo chmod 644 /usr/local/share/ComboJack/l10n.json
sudo cp com.XPS.ComboJack.plist /Library/LaunchDaemons/
sudo chmod 644 /Library/LaunchDaemons/com.XPS.ComboJack.plist
sudo chown root:wheel /Library/LaunchDaemons/com.XPS.ComboJack.plist
sudo launchctl load /Library/LaunchDaemons/com.XPS.ComboJack.plist
echo
echo "Please reboot! Also, it may be a good idea to turn off \"Use"
echo "ambient noise reduction\" when using an input method other than"
echo "the internal mic (meaning line-in, headset mic). As always: YMMV."
echo
echo "You can check to see if the watcher is working in the IORegistry:"
echo "there should be a device named \"VerbStubUserClient\" attached to"
echo "\"com_XPS_SetVerb\" somewhere within the \"HDEF\" entry's hierarchy."
echo
echo "Enjoy!"
echo
exit 0

Reboot and done.

This made it work for me.
